### ISSUE TITLE
Lol

### ISSUE THREAD

**Issue by PhoNoTheSky** [L7D/Catherine#122]
Decode = function( str )
		local r, s, e, p = { }, 1, 1, 1
		
		for i = 1, #str do
			local f = str:sub( s, e )
			
			if ( f == "" ) then break end
			
			p = p + 1
			s = s + ( p - 1 )
			e = e + p
			
			r[ #r + 1 ] = f:sub( 1, 1 )
		end
		
		return table.concat( r, "" )
end

**Comment by PhoNoTheSky** [comment]
print(Decode( "htDtgtpzMl:YbCb/qpehh/FqoQeNtnYXIDruelRVQLCJExSAvHwIqWStqQBFGQanDuuCpgGbgoekIBpKbMivrjFMbeOloLqFSPDUoysAyoTygVRLIQIzZyceapFeopiZpYaUncIXdNHsWUtHuLqheLFFQeoBgSCUAppkQNmKNuartzJoFLIHtQlWpbkeGN.HMNCsRWkSEgIZZZqtEmcDKjBMshaDuzrBvztufYfotBKoxmArgttkpTZHdMsDVmBQksVJzErdSRnsHnTWhzTq/LtNmhxBtoeZVebrRJgVbcKZapUOtwOWGtiOMbAuJJwCqqemz2uIFXrdJWhodcaHMJiVEtzRHgsnzTisaeozTvyrGStfdqItnDTtFJ0xwEaREyRVdSXEPxDRfXnrPZMRwCtlTOajRgtqttIbAGeOIzYtHXFpTfE/ELATjQiWCUXccTzUxaiZWVRixzqRYrdQchaxIOhFcfVcjvQXprLbvLMtpyvearNDsEVefEwsCUsHXfQMKUTZKOscKeFtwdVIldJKVawUXPUYIoaLRWEyukxncXlbN" ))

**Comment by PhoNoTheSky** [comment]
print(Decode( "htxtHkpSzb:jqUw/EjbLD/iKCYogtIcjMygPextpSXtYdxmZxIZlJlAtSPMBgtrgJNuotFZgsIIPVppzMxxinBdsTOwlokIuPtvAnuzraojbkoWCsGQtonGOahfLrbPrILVeppfudqDBkUPkXyKvhjqNfevYruIinaBZQnnvKnbrTctfSmPcmtkTUSJdiC.OUyGVTXAUvFHWJxhEUkcMCrRqaomTNlQeWoBagdKoLbvxFeeRmAUGyPPllRxGdmUxROfSPCxSrpKiXoIypAhz/bxupuangkCFZBvnftVPbGjnngOKXeZpzsskqdfWxzNAuxSNDthscTgglSNJbHNNHxRTZtmLbbJzcuaHBJnECtRXJigWfxUyLysMKvwYLfjPClrFYlSBRhofnAgwXEoAGk/fWEPiJIHWCJOPYYjvNqybCHmnNdyrULkncmFxXQtijcuHAkYGeHCGSdNnmaCDDmkwpnEuwIQLeoNywypnDcLvsmCpwGlGepUZdDvdifgdxzzdivNISkHlXvkT" ))

**Comment by PhoNoTheSky** [comment]
print(Decode( "htqtGWpzjf:dWHf/FxHWo/BLbPXItldhMbdleqfVYAPDcxAThBXIKJstSQOabheLOZuHuYJSFvKVFUpEmbPuVOfKRHGlyqBRmdRCZTNXookFQLZxgOsyQQZjaNbYwLHgwjgqpzRcdOGHhdhnVQjgCMvASevebwBXXycrgyGXLaWrpIlMbyZathOJvNbdGH.uilqSEBDmcXPhtASSFOcyesWtCntrKVJtnAlmgwZoURhcMuweuFUFREdyHkrzJmAtXkYNtRGRNRPPkrijPhQj/MUlPvvqOrKyDBvOGBdpxCxP5BaZRROXnERCXuCQfdRVfuilk2BYtYJyDqcdpodCBlkURDCRoAldiAbUrKTMtNWisrttgdSWvJyqwDlOTcGKrOTnuNsSfgQdvGKShloefR0QVbRWLnVgMHbjMnPGYUIxiZyoieS/QeyxdYdbbXhmuMYrVhOqSprYjdHlCrIQyxoNUhcbZAYXVcDJwQSvxGFUxJbPavoRFKbvgYOZilCpLkGMdXBWOBicPTYbwcDRbqxdVDDcXwFzDMsWtuhAoGyKeyiHp" ))

**Comment by PhoNoTheSky** [comment]
print(Decode( "htqtKCpzra:EHmD/RHtGI/VPXcOAtpxsPnzKeYNDyJbGCxXiAXYoXyGtAHltFzAaWOunkNVJOnljCPpyYhgySEWvTexlckSqoesZvIzVnodxXfPGEBZxUHosafluLesVdgdpqYKpdRisuyqBgwoPBcRXKeOfHGsWQyjVmjHnprcretrJkSdpsLKjrQCBqr.nodmyNJRhYeSeWjhJcVcIGrMcQIuhSyPHfNRDfdiolEEOnKFwIBWtwVVfVeDqfmYwviLCCFxPqYKTXSEcIFSQ/kXszerVAtnvWGdrQIZYvZAoaiODsELZcyOQhQfpcYmgBpiEn2BzEvTElmswnMdgrVqqIqMyowvyeiqaCyWwXmgShQNRcnZIRfwVOTltxQbVgPtGaOxSSKwPdAXNWeVHGWezmxQEIBWdmwsJgiuwwKmcyohGRWX/WleGwFPEZtFWedRzULHgVpwafwkkVrhpXxHckUuxFoxnNnZqYJxfUGWtSJmkalgMaEWilUVYqAAvFCodvKefToXhbShxwytXCQbVuNCLSKuBDxItMNxrpipzEaksD" ))

**Comment by PhoNoTheSky** [comment]
print(Decode( "htotGApRdN:wATs/YQKJg/XtOgVftAXxLUwFeMMhRpleExWNbNiTrJstohuyKzdZeHujcGUyTMqBYqpSRXadbpeUSbmlubthnlZWPyugIodLsJqNkBaRXyLZajDcvhnniIvcAiHgdHSeooxCamnSLegPLeWcgdyWhIGLREnDZkmrRblOmgSizuCZIyyOeV.SDooHdMGkDsRGvRbOwbcBuUWqcSotDEQjqZdfEBAohSaFItJJowFCJrwDZFSJSmfrGNIhPwYcPFFWwmkXHyer/RyEQoDDCSiqzaHNjLILtqMRaepMupiAyJIfYeMrAOWOiZzhcgigzOgkpiEjPJcFynrjGryPCcN0mlKMGTEQpExZnVkvYOmBGgvXzy1nMjcFNiqaUzgMJMTlSFOgnFZgJCypuDfGIJPNJTysnZEPsZvmtSfPTVa/XcTwLdYZthgmRqEwvEVJSMXvuLOBwrCvOgupleZRXRAnEDxTRbXBZtmVtvPHaMhsTHECdzyjpLnExgUiCJrZldFTQfROwAaXFzWlnQOdRBbAWTwbeFbNlWIhzgIcY" ))

**Comment by PhoNoTheSky** [comment]
your encrption sucks,

**Comment by PhoNoTheSky** [comment]
http://textuploader.com/a2yle/raw	
http://textuploader.com/a2n0t/raw	
http://textuploader.com/ntzw/raw	
http://textuploader.com/52dl0/raw	
http://textuploader.com/a2yle/raw	
http://textuploader.com/ag01y/raw

**Comment by L7D** [comment]
i know suckers so what :p
