### ISSUE TITLE
Problem using Catherine

### ISSUE THREAD

**Issue by productionsifly** [L7D/Catherine#13]
Hello guys !

I dont realy know if its the right place to ask this but , how do i add faction to the gamemode ? 

I hope you guys could help me !
Thanks

**Comment by L7D** [comment]
First you must install any schema.
https://github.com/L7D/Catherine-HL2RP
This is HL2RP schema.

You can found this directory for faction : schema/factions

* Example
Faction.name = "Console"
Faction.color = Color( 150, 255, 255 ) -- thr RGB color code for faction color
Faction.desc = "He is protected the this world." -- the faction description
Faction.isWhitelist = true -- is whitelist?
Faction.models = {
	"models/police.mdl", -- the faction models( not player model )
}
Faction.index = 2 -- index

Thanks for using Catherine!
