### ISSUE TITLE
Recognizing Bug

### ISSUE THREAD

**Issue by WulfieWS** [L7D/Catherine#16]
When I went to let my friend Recognize me with F2 and chose Yelling Range, my name did not change for him. but his name changed to mine for me.

![image](https://cloud.githubusercontent.com/assets/11455305/6635248/c97b9dac-c920-11e4-9c8d-affcb2a7d87e.png)

**Comment by L7D** [comment]
I fixed that bug, sorry for late.
Thanks for using Catherine!
