### ISSUE TITLE
OTA Animation bug

### ISSUE THREAD

**Issue by WulfieWS** [L7D/Catherine#18]
![image](https://cloud.githubusercontent.com/assets/11455305/6649651/283741ca-c9ad-11e4-8518-33db8b1378bc.png)
Weapon: Fist

**Comment by L7D** [comment]
I fixed that, sorry for late :)
![2015-03-14_00001](https://cloud.githubusercontent.com/assets/6937608/6649801/ad536bc4-ca37-11e4-96c7-2d64e3059a6f.jpg)
