### ISSUE TITLE
Some issue using Catherine

### ISSUE THREAD

**Issue by productionsifly** [L7D/Catherine#25]
I been looking for an option to set spawn of faction without finding anything , maybe you should add it...

Also I' ve some bug using this shema , all my guns  are in "safe" and i can not use them... 
http://cloud-4.steamusercontent.com/ugc/711906002235840660/6AFE440910FC70A6FE9CE7C204EAABC6F7F6420C/

I using FAS so i was thinking this would be due to FAS conflict but when i start the server without FAS , the bug is still happening. Also when i' m changing the gamemode to sandbox , everything is fix so i suppose its du to catherine

**Comment by Rubberbandits** [comment]
Hold R to raise or lower your weapon.
