### ISSUE TITLE
Lua Errors!

### ISSUE THREAD

**Issue by TheVingard** [L7D/Catherine#26]
So I load my Server with Catherine installed (and the hl2rp schema) and get this, constntly:

[ERROR] lua/includes/modules/gamemode.lua:86: attempt to index upvalue 'hook' (a nil value)
  1. Call - lua/includes/modules/gamemode.lua:86
   2. GetDefaultSkin - lua/derma/derma.lua:177
    3. GetSkin - lua/includes/extensions/client/panel.lua:354
     4. GetSkin - lua/includes/extensions/client/panel.lua:349
      5. GetSkin - lua/includes/extensions/client/panel.lua:349
       6. SkinHook - lua/derma/derma.lua:199
        7. unknown - lua/vgui/dtextentry.lua:280

---------------------------------------

So, please could you help. Server IP: 185.38.149.32:27075
Password: seriousrp

**Comment by L7D** [comment]
I don't know that error, sorry
Can you steam friend invite to me?
http://steamcommunity.com/profiles/76561198011675377

Thanks for using Catherine!
