### ISSUE TITLE
Chatbox Problems

### ISSUE THREAD

**Issue by Imacc2009** [L7D/Catherine#29]
1. Your Steam name is displayed, rather than your char name.
2. OOC icon is too big.

Screenshots:
![screenshot](https://cloud.githubusercontent.com/assets/5310715/6683083/0ed2af66-cc79-11e4-9243-f9edab9c6a69.png)

**Comment by L7D** [comment]
I fixed that bug, sorry for late.
Thanks for using Catherine!

**Comment by Sweetnut1018** [comment]
I'm using Catherine Developement 0.9, but I have same problem.
