### ISSUE TITLE
Issue With FAS

### ISSUE THREAD

**Issue by productionsifly** [L7D/Catherine#32]
I' m using FAS Weapon and i've notice that the "safe" system for weapon like physic gun & tool gun is creating conflict with the safe weapon system from FAS ( This is my point of view ) 

So if you use FAS With catherine , you will notice that you player is holding his weapon in safe mod all the time ( even is the weapon is not is safe ) Here is a screen : 
http://cloud-4.steamusercontent.com/ugc/709654652718059038/340C8D0FF095A4D25F3B4FFADBBF9E3F3B9D78C6/

In the screen i' m firing but my player is still holding the weapon in safe ^^

**Comment by productionsifly** [comment]
After checking back , if you old R for 5-10 sec , the weapon is back as normal. The only problem is that for the player (view model) There is no difference between the safe mode and the firing mode ( in world model )

**Comment by L7D** [comment]
Did you add models to class?
https://github.com/L7D/Catherine/wiki/anim
