### ISSUE TITLE
Workshop items glitch (Only some)

### ISSUE THREAD

**Issue by redaxel123** [L7D/Catherine#53]
When I equip some workshop guns such as Day of defeat source weapons or gmbombs 5 gasmasks (Gasmasks only cause this when unequiped) It causes my character to run (when I should be walking) when this happens I don't lose stamina. In order to stop running I either have to reconnect or hold alt.

**Comment by L7D** [comment]
Can you take link that addon?

**Comment by L7D** [comment]
Okay
