### ISSUE TITLE
Chessnut의 'Moderator' 애드온을 !spawn 명령어를 사용할 때 발생하는 오류

### ISSUE THREAD

**Issue by Sweetnut1018** [L7D/Catherine#89]
플레이어 사망 시, 관리자가 !spawn 명령어로 플레이어를 스폰시키면, 스폰 지점이 아닌 죽은 위치에서 스폰되고 체력이나 목마름 등의 수치, 탄약 같은 게 초기화가 안되고
그 뒤로 리스폰 시간이 지나면 (그 동안에는 플레이어가 멀쩡히 돌아다닙니다.) 스폰 지점에서 다시 스폰되게 됩니다.

**Comment by chino1120** [comment]
USE UXL! :(

**Comment by Sweetnut1018** [comment]
Just little, ULX IS SUCK.
How about make new brave 'Moderator' addon for Catherine?

ANYWAY, ULX IS SUCK.

**Comment by Sweetnut1018** [comment]
Why ULX Suck?

First, hell damn interface... omg.
Second, suck  @ and @@, /me

**Comment by chino1120** [comment]
Catherine was made of ulx.
Just use ulx :p

**Comment by Sweetnut1018** [comment]
첨언하건데, 캐서린에 특화된 관리 애드온이나 관리 패널을 추가하는 게 어떨까요?

**Comment by L7D** [comment]
Fixed - 2015-10-15 PM 9:18
