### ISSUE TITLE
노클립에 대한 몇가지 제안

### ISSUE THREAD

**Issue by Sweetnut1018** [L7D/Catherine#96]
노클립을 할 경우에 이 정도만 추가된다면 굉장히 편리할 것 같습니다.
NPC의 어그로를 해제하고, 3인칭을 노클립 도중네 잠시 풀었다가 노클립을 해제하면 다시 적용된다거나
노클립으로 빠르게 이동 중에 생기는 극심한 흔들림 효과를 잠시 멈춰준다던다 하는 것들 말입니다.

**Comment by L7D** [comment]
Updated - 2015-10-15 PM 6:35
